language: node_js
node_js:
  - "8"

before_install:
# grant the needed permission for deploy.sh
  - chmod +x deploy.sh
# DONT SETUP GH_TOKEN here, set it in Travis to avoid the security issue
# git setup
  - git config --global push.default matching
  - git config --global user.name "gasolin via Travis CI"
  - git config --global user.email "gasolin@gmail.com"
# github user name
  - export ACCOUNT=gasolin
# github project name
  - export REPO=ghpage-auto-deploy
# the folder that will be upload to gh-page
  - export FOLDER_TO_UPLOAD=build
# target export branch
  - export BRANCH=gh-pages
# check /usr/share/zoneinfo/ for valid timezone
# used in auto commit message
  - export TIMEZONE=Asia/Taipei

install:
  - npm install

script:
# your build process
  - CI=false npm run build
# deploy via travis
# check details on https://github.com/gasolin/ghpage-auto-deploy
  - ./deploy.sh

branches:
  only:
# the source branch
    - master

cache:
  directories:
    - node_modules
